name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 16
      uses: actions/setup-node@v4
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Start app in background
      run: |
        npm install -g wait-on
        npm start &  # Levanta el server en segundo plano
        wait-on http://localhost:3000

    - name: Run Cypress tests
      run: npx cypress run

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "Iniciando despliegue remoto..."

          echo "Eliminando versión anterior de la app..."
          rm -rf appDir && mkdir appDir

          echo "Clonando repositorio..."
          git clone https://${{ secrets.GH_TOKEN }}@github.com/martinchogimenez/pipeline-nodejs-cypress.git appDir
          cd appDir

          echo "Verificando Node.js..."
          if ! command -v node &> /dev/null; then
            echo "Node.js no está instalado. Instalando..."
            if [ -f /etc/debian_version ]; then
              curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
              sudo apt-get install -y nodejs
            elif [ -f /etc/redhat-release ]; then
              curl -fsSL https://rpm.nodesource.com/setup_16.x | sudo bash -
              sudo yum install -y nodejs
            fi
          else
            echo "Node.js ya está instalado."
          fi

          echo "Instalando dependencias..."
          npm install

          echo "Verificando PM2..."
          if ! command -v pm2 &> /dev/null; then
            echo "PM2 no está instalado. Instalando..."
            sudo npm install -g pm2
          else
            echo "PM2 ya está instalado."
          fi

          echo "Reiniciando aplicación con PM2..."
          pm2 stop all || true
          pm2 start index.js --name app
          pm2 save

          echo "Despliegue finalizado con éxito."
