name: CI Pipeline - Cypress + SSH Deploy

on:
  push:
    branches:
      - main

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  REMOTE_USER: ec2-user
  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Start app and run Cypress tests
        run: |
          npm run dev &
          sleep 5
          npx cypress run

      - name: Deploy to Remote Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ env.REMOTE_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            sudo yum update -y

            # Instalar Node.js 18.x (si no está)
            if ! command -v node &> /dev/null; then
              curl -fsSL https://rpm.nodesource.com/setup_18.x | sudo bash -
              sudo yum install -y nodejs
            fi

            # Instalar git si no está
            if ! command -v git &> /dev/null; then
              sudo yum install git -y
            fi

            # Instalar pm2 si no está
            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi

            # Clonar o actualizar el repo
            cd /opt
            if [ -d "appDir" ]; then
              cd appDir && git pull origin main
            else
              git clone https://${{ env.GH_TOKEN }}@github.com/martinchogimenez/pipeline-nodejs-cypress.git appDir
              cd appDir
            fi

            # Instalar dependencias y reiniciar app
            npm install
            pm2 delete all || true
            pm2 start src/index.js --name users-api
            pm2 save